### ISSUE TITLE
Allow for github URL be used instead of just repo identifier

### ISSUE THREAD

**Issue by SVNKoch** [8LWXpg/ptr#8]
instead of just
`ptr a GitHubRepo 8LWXpg/PowerToysRun-GitHubRepo`
I'd like to use
`ptr a GitHubRepo https://github.com/8LWXpg/PowerToysRun-GitHubRepo`

**Comment by 8LWXpg** [comment]
I don't like the idea of adding extra unnecessary information to arguments, and I assume that adding plugins 
are used infrequently. I may need to think more about it.

If you just want an easier copy-pasting from GitHub, it can be done easily with a PowerShell script:
```pwsh
param (
	[Parameter(Mandatory)]
	[string]
	$name,

	[Parameter(Mandatory)]
	[string]
	$url
)

ptr a $name ($url -replace 'https://github.com/','')
```
Save it to a file like `ptra.ps1` and call it in PowerShell with `ptra <name> <url>`.

**Comment by neilenns** [comment]
Came to open this request, see that it was already requested once before.

Please reconsider :) I keep trying to add via the URL because it's a fast copy/paste from my browser address bar, and get a cryptic "Failed to fetch latest: Not Found" error.

I don't think you need to add a new parameter for this, just make the existing argument more forgiving and accept both formats.

**Comment by neilenns** [comment]
Super cool! Thank you!
